name: notes2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: '^2.0.15'
  shared_preferences: '^2.2.0'
  provider: ^6.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: Handjet
      fonts:
        - asset: fonts/Handjet-Bold.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf
